export const API_URL = "https://api.themoviedb.org/3"
export const API_KEY = "9e4c3fcb0bd143d3f148695d8749741b"
export const IMG_LINK = "https://image.tmdb.org/t/p/w500"
export const IMAGE_URL = "https://image.tmdb.org/t/p/original"
export const ID_URL = "https://api.themoviedb.org/3"